### ISSUE TITLE
Wallpaper Engine Integration

### ISSUE THREAD

**Issue by LemuelDayrit** [luisbocanegra/plasma-smart-video-wallpaper-reborn#38]
Is there a chance that it can integrate live wallpapers from Wallpaper Engine because i do have many live wallpapers which is a waste because the other plugin seems deprecated

**Comment by luisbocanegra** [comment]
If you mean scanning your video files from the steam wallpaper engine library (or any folder for that matter), I think I can add that.

If you mean supporting the wallpaper engine presets format with the previews and all (or media other than video) that's out of scope.

> the other plugin seems deprecated

It is not :)

There is recent work on the https://github.com/catsout/wallpaper-engine-kde-plugin/tree/qt6 branch, it just hasn't been merged probably because it isn't ready yet. I tried with some video presets and it seemed to work fine.

**Comment by LemuelDayrit** [comment]
i tried that but some wallpapers turn into gray
