### ISSUE TITLE
[Bug]: Background goes to black and seems to crash KDE, then reverts to previous settings.

### ISSUE THREAD

**Issue by iseal56** [luisbocanegra/plasma-smart-video-wallpaper-reborn#49]
I have:

- [x] Searched if this issue hasn't been reported yet.
- [x] Verified that I am using the latest version (run `grep '"Version"' {~/.local,/usr}/share/plasma/wallpapers/luisbocanegra.smart.video.wallpaper.reborn/metadata.json` or from *Wallpaper settings* > *top right corner for version 1.0.0 and later*), **should be the same as [https://github.com/luisbocanegra/plasma-smart-video-wallpaper-reborn/releases/latest](https://github.com/luisbocanegra/plasma-smart-video-wallpaper-reborn/releases/latest)**

**Describe the bug**
When you click on apply, the background goes black and then goes back to the old settings

**To Reproduce**
1. Set your background as anything but the video wallpaper plugin - ex. Plain color or Image
2. Configure the smart video wallpaper
3. Click apply
4. Watch the crash

**Observed Result**
The desktop seems to crash and revert back to the original state

*Please describe and attach terminal error output (if any)*
-- no idea what I'm supposed to attach here

**Expected Result**
The video starts playing in the background

**Screenshots**
I'll attach a video demonstrating the problem
https://github.com/user-attachments/assets/9f227387-75e1-4f6d-845d-eec43408bf49
^^

**System information (please complete the following):**

- Operating System: Arch Linux
- KDE Plasma Version: 6.2.4
- KDE Frameworks Version: 6.9.0
- Qt Version: 6.8.1
- Graphics Platform: Wayland
- Things in your system that might be relevant: ask me anything, i don't really know what to add here

**Additional context**
I'm using the mesa drivers with Iris Xe graphics
I'm using the plasma-desktop package, so its a minimal install

**Comment by luisbocanegra** [comment]
Hi, @iseal56

Please attach the `journal.txt` file you created when when reproducing the crash.

**Comment by iseal56** [comment]
My bad, here are they:
[dmesg.txt](https://github.com/user-attachments/files/18222991/dmesg.txt)
[journal.txt](https://github.com/user-attachments/files/18222992/journal.txt)

**Comment by luisbocanegra** [comment]
Hmm, It appears to be a missing dependency

```
plasmashell[8883]: Failed to initialize QAudioOutput "Could not find the autoaudiosink GStreamer element"
```

What's the output of `echo $QT_MEDIA_BACKEND` and `pacman -Qq | grep "^qt6-multimedia"`?

**Comment by luisbocanegra** [comment]
The default Qt media back-end should be ffmpeg/pulseaudio (`echo $QT_MEDIA_BACKEND` prints nothing), unless you or something else in your system changed it. Changing the media back-end as described in the [readme](https://github.com/luisbocanegra/plasma-smart-video-wallpaper-reborn?tab=readme-ov-file#possible-solution-switching-to-gstreamer-as-qt-media-backend) is a possible workaround for crashes, but those happen mostly on AMD GPU and haven't seen that problem with Intel ones.

Also I am not sure if I should have instead specified  what the widget requires `qt6-multimedia-ffmpeg` specifically as a dependency, instead of `qt6-multimedia` alone as it depends on `qt6-multimedia-backend`, which is provided by both `qt6-multimedia-ffmpeg` and `qt6-multimedia-gstreamer`, but since you're on a minimal install I think you can help me to clarify that :)

Can you check which one you got installed? If `qt6-multimedia-ffmpeg` is not installed and `echo $QT_MEDIA_BACKEND` is empty try installing it and rebooting, if that could solve the problem

**Comment by iseal56** [comment]
I had followed the fix in the readme and it apparently messed it up. I reverted that and installed ffmpeg as the backend and now it seems to work flawlessly.
You should probably add a note for that 😅 
Thanks for helping!

**Comment by luisbocanegra** [comment]
> I had followed the fix in the readme and it apparently messed it up. I reverted that and installed ffmpeg as the backend and now it seems to work flawlessly.
> You should probably add a note for that 😅 
> Thanks for helping!

You're welcome! I'll update the readme.
